### ISSUE TITLE
Chapters 4-9 have disappeared from kickstart-docs.rst

### ISSUE THREAD

**Issue by christopher-ursich** [rhinstaller/pykickstart#107]

**Comment by atodorov** [comment]
@clumens - how quickly can you get ReadTheDocs working ?

**Comment by clumens** [comment]
I was working on it some on Friday.  It can't find versionremoved, for reasons I haven't been able to figure out:  https://readthedocs.org/projects/pykickstart/builds/4486379/

**Comment by clumens** [comment]
Getting closer:  https://readthedocs.org/projects/pykickstart/builds/4496608/

**Comment by clumens** [comment]
I think we're going to have to commit commands.rst, commands_rhel.rst, and sections.rst to the repo.  From looking at the commands being run, it doesn't look like RTD wants to generate those files and making it do so seems like an awful lot of work.

**Comment by atodorov** [comment]
@clumens IIRC ReadTheDocs uses its own make commands, not what you supply in the repo so yeah, we'll have to commit these files to git. Do you have a good way to ensure that these files are regenerated when we change the help descriptions or update the commands ? We can't expect folks to execute them on every commit but we certainly can automate for that. Thoughts ?

**Comment by clumens** [comment]
I can't think of any way to do that, no.  However I could at the least add it to the "make bumpver" process so it gets regenerated every time I make a new release.  That might be often enough.

**Comment by clumens** [comment]
Okay, the next version of the package should have a complete kickstart-docs.txt in it.  Next step is making sure people know to look at readthedocs.
