### ISSUE TITLE
"ks=" options seem to have been renamed to "inst.ks=" as of Fedora 21

### ISSUE THREAD

**Issue by profwpollock** [rhinstaller/pykickstart#109]
The documentation here still uses "ks=", but apparently that (and other options) have changed.  The docs for RHEL 7 also use the newer options.  Is this documentation obsolete (only for RHEL 6), or will it be updated?

**Comment by clumens** [comment]
Updated, thanks for bringing this up.  The short answer is that you should use the inst.ks= form starting in F17 and RHEL7, but the older form is still recognized (for now).
