### ISSUE TITLE
Error parsing timezone command for RHEL7

### ISSUE THREAD

**Issue by skywalk7** [rhinstaller/pykickstart#112]
Source kickstart:
`timezone --utc America/Los_Angeles`

Error:
```
The following problem occurred on line 18 of the kickstart file:

One or zero arguments are expected for the timezone command
```

I think the problem is here:
```
        ...
        if ns.timezone:
            if len(ns.timezone) == 1:
                self.timezone = ns.timezone[0]
            elif len(ns.timezone) > 1:
        ...
```
ns.timezone holds name of the timezone, so in my case len(ns.timezone) was 19.
I would remove the whole `if ns.timezone:` case, but not 100% sure.

**Comment by atodorov** [comment]
@skywalk7 you are right, this was introduced as part of my patches for automated documentation. I've been working on some tests today and will submit a PR fixing this in a few minutes. If you are curious the fix is very simple:

```
-        op.add_argument("timezone", metavar="<timezone>", nargs="?",
+        op.add_argument("timezone", metavar="<timezone>", nargs="*",
```

this instructs argparse to always treat the argument as a list.
