### ISSUE TITLE
Unable to find packages to install from an USB drive with "harddrive" or "url --> file:///" option

### ISSUE THREAD

**Issue by q2dg** [rhinstaller/pykickstart#125]
Hello.

I want to use an USB pendrive to do unattended installations of Fedora Server.
I append the inst.ks=hd:LABEL=myUsbLable:/ks.cfg parameter to boot menu (but no inst.stage2 nor inst.repo) and it's ok because Anaconda starts well and find the ks file. My problem is with "install" option.

If I do...:
_install
harddrive --partition=sdb1 –dir=/_
...Anaconda GUI starts ok but shows "source is invalid" (although it specified partition is correctly selected). I think it's because Anaconda expect an iso file but what I have is the expanded tree.

If I do...:
_install 
url –url=file:///run/install/repo  (or url --url=file:///run/install/isodir)_
...a dracut error appears saying that "inst.repo" is not a valid location.

I don't think I'm trying to do something strange...this use case must be very common, isn't??. What's the problem?? Is it a bug??

EDIT: I'm using Fedora 24

**Comment by clumens** [comment]
These appear to be anaconda errors, and not problems with parsing the kickstart file itself (which is what pykickstart does).  I think they're still using RH bugzilla for anaconda, so if you could please open a bug at http://bugzilla.redhat.com under the anaconda component, they'll take a look.  Thanks!

**Comment by q2dg** [comment]
Ok, done: https://bugzilla.redhat.com/show_bug.cgi?id=1389840
Thanks!
