### ISSUE TITLE
Make Kickstart files understood by Workstation edition

### ISSUE THREAD

**Issue by q2dg** [rhinstaller/pykickstart#126]
Hello.

I want to install a Fedora Workstation with a Kickstart file but inst.ks parameter isn't recognized in this kind of Fedora iso: it only works on Fedora Server edition. This is a pity because using Server edition I can't install Gnome (or any) desktop environment; that's a big limitation!

Thanks

**Comment by clumens** [comment]
These appear to be anaconda errors, and not problems with parsing the kickstart file itself (which is what pykickstart does).  I think they're still using RH bugzilla for anaconda, so if you could please open a bug at http://bugzilla.redhat.com under the anaconda component, they'll take a look.  Thanks!

**Comment by q2dg** [comment]
Ok, done: https://bugzilla.redhat.com/show_bug.cgi?id=1389841
Thanks!
