### ISSUE TITLE
Docs: Chapter 5 introduction talks about *comps.xml which is not matched.

### ISSUE THREAD

**Issue by lf-** [rhinstaller/pykickstart#135]
http://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#chapter-5-package-selection

On my fedora DVD, I see 9e5d05c29606132f8f8862f7941cbbc076414ecf9ae3070d30312de5d69902b4-comps-Server.x86_64.xml which does not match `*comps.xml`. Perhaps this should be changed to `*comps*.xml`?

**Comment by clumens** [comment]
Pushed a fix, which should show up on readthedocs soon.  Thanks!
