### ISSUE TITLE
Please parse and write %addon sections

### ISSUE THREAD

**Issue by lpancescu** [rhinstaller/pykickstart#154]
I'm trying to disable kdump in the CentOS Vagrant images, but the resulting kickstart that `kojid` creates for the builder has the following section simply stripped out:

```
%addon com_redhat_kdump --disable
%end
```

Simply omitting this section is unfortunately not a noop, since the default is to include kdump.

**Comment by clumens** [comment]
This is a side effect of how the %addon section is implemented.  It's recognized by pykickstart, but only far enough to not crash when a kickstart file with one is seen.  All the actual work to support it is done in anaconda.  This will take a bit of work I think.

**Comment by clumens** [comment]
Okay, maybe not all that much work.  Pushed a cheesy fix.
