### ISSUE TITLE
pykickstart in pypi?

### ISSUE THREAD

**Issue by hairesis** [rhinstaller/pykickstart#162]
For testing purposes I would find useful having pykickstart as a python package (e.g. to install into a venv). Is there a reason why it is not present in pypi.python.org anymore?

**Comment by clumens** [comment]
I don't remember ever doing anything to enable pypi, nor to disable it.  So, I have no idea how it would have gotten there in the first place let alone no longer be there.  If there's something I can do to fix it, let me know.

**Comment by hairesis** [comment]
If there is not particular limitation, it would be nice to have it in pypi. I'm writing some ansible modules and it would simplifying testing.

**Comment by clumens** [comment]
Aha, I do actually have a .pypirc file, created in 2012.  I must have done this a while back and forgotten.  I'll take a look at getting sdists on pypi automatically as part of the build process.

**Comment by clumens** [comment]
I've pushed the master version of pykickstart to pypi.  Built versions of that are available from a COPR.  When I do a new release from the pykickstart-2 branch (which is what anaconda and stuff is using right now), I'll push that too.  I hope pypi supports multiple versions of the same thing.

Anyway there's bound to be more bugs around this.  Feel free to open new reports.
