### ISSUE TITLE
Error downloading package metadata on Fedora 26

### ISSUE THREAD

**Issue by sedrubal** [rhinstaller/pykickstart#195]
I tried to setup a new Fedora 26 Server Edition ([network installation image](https://getfedora.org/en/server/download/server-download-splash?file=https://download.fedoraproject.org/pub/fedora/linux/releases/26/Server/x86_64/iso/Fedora-Server-netinst-x86_64-26-1.5.iso)) using the kickstart file below. It is mostly automatically configured by anaconda with some modifications.

Unfortunately there is an error when setting up the installation sources:
![spectacle lh7367](https://user-images.githubusercontent.com/5571650/32282654-750b93f8-bf22-11e7-96b9-ee9be3818ac9.png)

Some (relevant) lines from the log on TTY1:
```
anaconda: spoke is not ready: SourceSpoke
anaconda: setting SourceSpoke status to: Downloading package metadata...
anaconda: setting SourceSpoke status to: Downloading group metadata...
anaconda: setting SourceSpoke status to: Error downloading package metadata...
anaconda: kickstart installation stopped for info: User interaction required on spoke INSTALLATION SOURCE
```

Steps I did yet:
- When I try to set up the sources manually, this does not work neither. I've chosen "On the network", "Closest mirror", but it does not work.
- When I don't add a kickstart file, everything works as expected
- The machine is connected to the internet
-  I can download the metalist from mirrors.fedoraproject.org using curl
-  I can download the repomd.xml from at least one mirror using curl

kickstart.cfg:
```cfg
#version=DEVEL
# System authorization information
auth --enableshadow --passalgo=sha512
# Use graphical install
graphical
# Run the Setup Agent on first boot
firstboot --enable
ignoredisk --only-use=sda,sdb,sdc,sdd
# Keyboard layouts
keyboard --vckeymap=us --xlayouts='us'
# System language
lang en_US.UTF-8

# Network information
network  --bootproto=dhcp --device=enp0s20f0 --ipv6=auto --activate
network  --bootproto=dhcp --device=enp0s20f1 --ipv6=auto
network  --bootproto=dhcp --device=enp0s20f2 --ipv6=auto
network  --bootproto=dhcp --device=enp0s20f3 --ipv6=auto
network  --hostname=xxx.xxx.de
# Root password
rootpw --iscrypted $6$xxx$xxx
# System services
services --enabled="chronyd"
# System timezone
timezone Europe/Berlin --isUtc --ntpservers=2.fedora.pool.ntp.org,2.fedora.pool.ntp.org,2.fedora.pool.ntp.org,2.fedora.pool.ntp.org,ntp0.fau.de,ntp1.fau.de,ntp2.fau.de,ntp3.fau.de
user --groups=wheel --name=xxx --password=$6$xxx$xxx --iscrypted --gecos="xxx"
sshkey --username=xxx "xxx"
sshkey --username=xxx "xxx"
# System bootloader configuration
bootloader --location=mbr --boot-drive=sdc
# Partition clearing information
clearpart --all --initlabel
# Disk partitioning information
[...]

%packages
@^server-product-environment
chrony

%end

%addon com_redhat_kdump --disable --reserve-mb='128'

%end

%anaconda
pwpolicy root --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy user --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
pwpolicy luks --minlen=6 --minquality=1 --notstrict --nochanges --emptyok
%end
```

**Comment by jkonecny12** [comment]
Hello,

Please file this bug in the [bugzilla](http://bugzilla.redhat.com/) for the Anaconda component and attach logs /tmp/*.log as pain/text files from the installation environment.

Thanks for report.

**Comment by sedrubal** [comment]
Thanks, I opened this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1509527
