### ISSUE TITLE
Older versions in new Fedora releases than in the older ones

### ISSUE THREAD

**Issue by vpodzime** [rhinstaller/pykickstart#28]
When updating the *pykickstart/handlers/f23.py* file's ``logvol`` handlers I figured out that for example the *f23.py*'s ``logvol`` handler was set to an older version of the ``LogVol`` class than the *f21.py*'s handler. The same applies to the *f22.py*'s handler. 

See @bcl's comment in PR #26 (https://github.com/rhinstaller/pykickstart/pull/26#discussion_r32790705).

**Comment by clumens** [comment]
Ugh, this is probably automatable, but it's going to be ugly.

**Comment by clumens** [comment]
On second thought, I don't think this is actually automatable with what we've got in pykickstart right now.  I'd have to add some data to objects to basically map command handler classes back to handlers.  I think.

**Comment by vpodzime** [comment]
I think we could at least add a test that would check (by importing ``comandMap``s) that newer handlers never use older classes.
