### ISSUE TITLE
RFE: Make docs more clear about when kickstart options were added

### ISSUE THREAD

**Issue by tflink** [rhinstaller/pykickstart#39]
The current doc for kickstart options isn't very clearly versioned - there is just a list of options. It would be much appreciated if a note indicating when options and sub-options were added could be added to the docs. This would lead to being able to know which options work on which Fedora releases without having to dig through git history.

**Comment by vpodzime** [comment]
I think this could be done by using git tags or branches for Fedora/RHEL releases.

**Comment by tflink** [comment]
Yeah, that'd work well as long as we can have direct links to the docs that don't need to be updated for every change. Some links to the docs would need to be updated but that's not a big deal and it would be much easier to figure out which options go with which releases

**Comment by Frodox** [comment]
+1 for that feature

**Comment by atodorov** [comment]
@tflink, @vpodzime, @Frodox can you review #85, it's a try to resolve this.
