### ISSUE TITLE
ostreesetup not listed in kickstart-docs.rst

### ISSUE THREAD

**Issue by atodorov** [rhinstaller/pykickstart#40]
How about instead of adding these one-by-one generate kickstart-docs.rst from the commands descriptions ? It may also resolve the issue with docs not being versioned at the moment.

**Comment by clumens** [comment]
Yes, I definitely do want to do that.  There just never seems to be time.

**Comment by clumens** [comment]
This is also being taken care of by https://github.com/rhinstaller/pykickstart/pull/85/

**Comment by atodorov** [comment]
Closing in favor of #85
