### ISSUE TITLE
Usage of authconfig is unclear

### ISSUE THREAD

**Issue by protel-opensource** [rhinstaller/pykickstart#71]
Actually you give an example of how to use it, but don't further document the detailed usage of authconfig.
In a status where there is no system initialized, or at least not a RedHat or Fedora System I need to rely on your documentation for authconfig but you simply refer to a manual page and don't give a reference link.
I don't have authconfig installed on my gentoo system, so I miss the manual page.
There are several implementations of what authconfig might be and one top hit, when I search the Internet for authconfig I get [authconfig@linuxcommand.org](http://linuxcommand.org/man_pages/authconfig8.html).

This manual page does not show the usage of --passalgo.

Also I have an old example that uses --useshadow instead of --enableshadow. So even you RedHat guys might use several versions of that software, that might have changed some time in the past and there is no link to the upstream project with a changelog to check when this has changed.

Please fix your documentation or don't use tools that are not unique or standardised.

**Comment by vpodzime** [comment]
Just a short note: is really easy to edit the documentation here at GH and submit a pull request with the fixes/amendments.

**Comment by vpodzime** [comment]
The man page *authconfig* provides on my Fedora 23 is the same as this one: http://linux.die.net/man/8/authconfig

**Comment by clumens** [comment]
Yeah, I'm much more interested in PRs that update documentation than issue reports.  I'm not actively using this as a bug tracker at all, in fact.
