### ISSUE TITLE
[RFE] %onfailure section

### ISSUE THREAD

**Issue by jcpunk** [rhinstaller/pykickstart#74]
Every so often I've got a failed kickstart.  It would be nice if I could add some behavior to execute if kickstart fails.  I'd love for it to drop me in the %pre environment mostly so I can (a) automatically transfer off the logs needed to troubleshoot why, (b) disable Foreman (Sat 6) install mode (c) possibly reboot the system.

Thoughts?

**Comment by clumens** [comment]
I like it.  This is similar to the undocumented %traceback section, but would be more broad in scope.  I assume you'd want to be able to run this in all failures?  Would you want some way of determining when in the process the failure happened?  What else would be useful?

**Comment by jcpunk** [comment]
My best case would be to have it called whenever any failure happens (or traceback) with the error/traceback passed in - effectively anytime the install did not complete.

The ability to parse out where it error-ed out would be nice (perhaps borrowing some logic from https://github.com/rhinstaller/anaconda/blob/master/docs/user-interaction-config-file-spec.rst ?)

My short term goal (A) is mostly to poke Foreman (Sat 6) to disable install mode and reboot the system.

My long term goal (B) is to get enough functionality here that RH Support can just provide a %onfailure section to add to a kickstart for collecting the needed debugging logs automatically (solutions/20358).

**Comment by cacoyle** [comment]
I think this would be great as well, especially if treated like `%pre` and `%post` where you can run arbitrary shell commands.

**Comment by jcpunk** [comment]
Just like ```%pre``` (though perhaps without ```/mnt/sysimage``` in ```$PATH```) would be an ideal place to run commands.  If we aborted the install, best not to trust anything hiding out there.

**Comment by clumens** [comment]
After spending a little time trying to figure out how we could let you know where the failure happened, I don't think it's really possible in any useful way.  The best I can come up with is providing the script with some argument to indicate position.  However, no system I've thought of is satisfactory.  File and line gives the exact position of the failure, but isn't actually useful.  Some single word ("vnc", "storage", etc.) is more useful but is less exact and is another form of API we'll have to maintain (and will definitely forget to).

So I think the best way to go is just have people examine /tmp/anaconda.log which will hopefully have the error message in it.  If that proves too difficult, I think we should spend our time around trying to make the last logged message be the error.

**Comment by cacoyle** [comment]
Even if it's a fairly generic catch-all, I think there's still value in providing it as an option to be able to phone-home on failure  Remote sites, for example, where your only insight into an unattended install failing might be based on time.

**Comment by clumens** [comment]
Yeah, it's definitely still worth providing the section.  I just don't think I can make it as fantastically useful as I was hoping.
