### ISSUE TITLE
RFE: copy kickstart files to /root/ks.cfg on installed OS

### ISSUE THREAD

**Issue by nkadel** [rhinstaller/pykickstart#84]
Many people who use kickstart files find the discrepancies between the actual kickstart file used for bulk deployment, and the published "/root/anaconda-ks.cfg", to be confusing and even invalidating. The "anaconda-ks.cfg", for example, does not reliably publish copies of multiple '%pre' or '%post' operations. Also, the re-arrangement of a valid kickstart file into the anaconda-ks.cfg default format, which does not match the format produced by the various "system-config-kickstart" tools, makes the direct comparision and source control of kickstart files additionally difficult.

So please: if a kickstart file is used, it is typically downloaded to /tmp/ks.cfg in the load environment. Simply execute a "%post --nochroot" like step and copy "/tmp/ks.cfg" to "/mnt/sysimage/root/ks.cfg"

**Comment by vpodzime** [comment]
Could you please submit a pull request with the change suggested above?

**Comment by nkadel** [comment]
If I can unfurl it from the more complex python, yes.

**Comment by clumens** [comment]
This would need to be done in anaconda, not pykickstart.  And I agree - we really should just copy it over in that case.  I'm sure we either did at one point or I talked about it a lot.  I don't know that github knows how to move issues from one component to another, unfortunately.  Could you please just copy this over to the anaconda project, or open a bug in RH bugzilla against anaconda?  Thanks!
